package View;

import Controller.UserControl;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Alejandro Juarez
 */
public class ActionCommittedsView extends javax.swing.JFrame {

    /**
     * Creates new form
     */
    public ActionCommittedsView() {
        initComponents();
    }

    /**
     * |
     * Will filter agreements table.
     */
    public void filterMovements() {
        TableRowSorter trsFiltro = new TableRowSorter(tblAgreements.getModel());
        if (chkMovement.isSelected() || chkDate.isSelected() || chkUserName.isSelected()) {
            if (chkMovement.isSelected()) {
                trsFiltro.setRowFilter(RowFilter.regexFilter(tfSearch.getText().toUpperCase().replaceFirst("O", "Ó"), 2));
            } else if (chkDate.isSelected()) {
                trsFiltro.setRowFilter(RowFilter.regexFilter(tfSearch.getText().toUpperCase(), 1));
            } else {
                trsFiltro.setRowFilter(RowFilter.regexFilter(tfSearch.getText().toUpperCase(), 3));
            }
        }
        tblAgreements.setRowSorter(trsFiltro);
    }

    /**
     * Will set the controller of this view.
     *
     * @param control
     */
    public void setController(UserControl control) {
        tfSearch.addKeyListener(control);
        btnMakeReport.addActionListener(control);
        btnMakeReport.setActionCommand("MAKE_ACTIONS_COMMITTEDS_REPORT");
    }

    /**
     * Gets the agreement number of the selected row.
     *
     * @return
     */
    public Long getSelectedAgreementNumber() {
        return Long.parseLong((String) tblAgreements.getValueAt(tblAgreements.getSelectedRow(), 2));
    }

    /**
     * Sets the model for the table.
     *
     * @param model
     */
    public void setTableModel(DefaultTableModel model) {
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.CENTER); //CENTER o LEFT
        tblAgreements.setModel(model);  //Setting model
        tblAgreements.setRowHeight(25); //Setting rows height
        tblAgreements.setFont(new java.awt.Font("Tahoma", 0, 18)); //Changing font
        tblAgreements.getTableHeader().setReorderingAllowed(false); //Disabling reordering columns
        for (int i = 0; i < tblAgreements.getColumnCount(); i++) {
            tblAgreements.getColumnModel().getColumn(i).setCellRenderer(tcr);
        }
    }

    /**
     *
     * @return
     */
    public JTextField getTfSearch() {
        return this.tfSearch;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnMakeReport = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAgreements = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        tfSearch = new javax.swing.JTextField();
        chkMovement = new javax.swing.JCheckBox();
        chkDate = new javax.swing.JCheckBox();
        chkUserName = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PADRON GENERAL DE CONVENIOS");
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setResizable(false);

        jPanel1.setLayout(new java.awt.BorderLayout());

        btnMakeReport.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMakeReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PDF.png"))); // NOI18N
        btnMakeReport.setText("Generar reporte");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 1081, Short.MAX_VALUE)
                .addComponent(btnMakeReport))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(btnMakeReport)
                .addGap(14, 14, 14))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        tblAgreements.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblAgreements);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        tfSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfSearch.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        chkMovement.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chkMovement.setSelected(true);
        chkMovement.setText("Busqueda por movimiento");
        chkMovement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMovementActionPerformed(evt);
            }
        });

        chkDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chkDate.setText("Busqueda por fecha");
        chkDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDateActionPerformed(evt);
            }
        });

        chkUserName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chkUserName.setText("Busqueda por nombre de usuario");
        chkUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkUserNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(chkMovement)
                .addGap(18, 18, 18)
                .addComponent(chkDate)
                .addGap(18, 18, 18)
                .addComponent(chkUserName)
                .addGap(18, 18, 18)
                .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkMovement)
                    .addComponent(chkDate)
                    .addComponent(chkUserName))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkMovementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMovementActionPerformed
        chkDate.setSelected(false);
        chkUserName.setSelected(false);
    }//GEN-LAST:event_chkMovementActionPerformed

    private void chkDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDateActionPerformed
        chkMovement.setSelected(false);
        chkUserName.setSelected(false);
    }//GEN-LAST:event_chkDateActionPerformed

    private void chkUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkUserNameActionPerformed
        chkMovement.setSelected(false);
        chkDate.setSelected(false);
    }//GEN-LAST:event_chkUserNameActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMakeReport;
    private javax.swing.JCheckBox chkDate;
    private javax.swing.JCheckBox chkMovement;
    private javax.swing.JCheckBox chkUserName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAgreements;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables
}
