/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.RegistrationControl;
import datechooser.beans.DateChooserDialog;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Alejandro Juarez
 */
public class AgreementRegister extends javax.swing.JFrame {

    /**
     * Creates new form Agreement
     */
    public AgreementRegister() {
        initComponents();
    }

    /**
     * Set the controller of this view.
     *
     * @param control
     */
    public void setController(RegistrationControl control) {
        this.btnSaveAgreement.addActionListener(control);
        this.btnSaveAgreement.setActionCommand("SAVE_AGREEMENT");
        
        this.btnSetTaxpayer.addActionListener(control);
        this.btnSetTaxpayer.setActionCommand("SELECT_TAXPAYER");
        
        this.btnNewTaxpayer.addActionListener(control);
        this.btnNewTaxpayer.setActionCommand("NEW_TAXPAYER");
    }

    /**
     * Adds one concept to the concept combo box.
     *
     * @param concept
     */
    public void setCmbConcept(String concept) {
        this.cmbSetConcept.addItem(concept);
    }

    /**
     * Sets the tfTaxPayer.
     *
     * @param taxpayer
     */
    public void setTfTaxPayer(String taxpayer) {
        this.tfTaxPayer.setText(taxpayer);
    }

    /**
     * Sets the tfAgreementNumber.
     *
     * @param number
     */
    public void setTfAgreementNumber(String number) {
        this.tfAgreementNumber.setText(number);
    }

    /**
     * Verifies the information is completed.
     *
     * @return
     */
    public boolean verifyInformation() {
//        if (cmbSetConcept.getSelectedItem().toString().equals("")) {
//            JOptionPane.showMessageDialog(this, "Advertencia", "El concepto de la deuda es obligatorio", JOptionPane.WARNING_MESSAGE);
//            return false;
//        }
        if (tfAmountOfDebt.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "El monto de la deuda es obligatorio", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if (tfDateOfCreation.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "La fecha de efectuacion del convenio es obligatoria", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if (tfDateOfExpiration.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "La fecha de vencimiento del convenio es obligatoria", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if (tfTaxPayer.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "La seleccion del titular del convenio es obligatoria", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }

    /**
     * Gets the agreement number from text field.
     *
     * @return
     */
    public String getTfAgreementNumber() {
        return tfAgreementNumber.getText();
    }

    /**
     * Gets the amount of the debt.
     *
     * @return
     */
    public String getTfAmountOfDebt() {
        return tfAmountOfDebt.getText().split(" ")[1];
    }

    /**
     * Gets the agreement date of creation.
     *
     * @return
     */
    public String getTfDateOfCreation() {
        return tfDateOfCreation.getText();
    }

    /**
     * Gets the agreement date of expiration.
     *
     * @return
     */
    public String getTfDateOfExpiration() {
        return tfDateOfExpiration.getText();
    }

    /**
     * Gets the agreement description from text field.
     *
     * @return
     */
    public String getTfDescription() {
        return tfDescription.getText().replace("    ", "");
    }

    /**
     * Gets the total number of cuots.
     *
     * @return
     */
    public String getCmbCuotsNumber() {
        return cmbSetCuots.getSelectedItem().toString();
    }

    /**
     * Gets the domain of the vehicle.
     *
     * @return
     */
    public String getCmbConcept() {
        return cmbSetConcept.getSelectedItem().toString().split(" : ")[0];
    }

    /**
     * Gets the domain of the vehicle.
     *
     * @return //
     */
    public String getTfVehicle() {
        return tfVehicle.getText().split(" : ")[0];
    }

    /**
     * Gets the domain of the vehicle.
     *
     * @return
     */
    public String getTfProperty() {
        return tfProperty.getText().split(" : ")[0];
    }

    /**
     * Gets the domain of the vehicle.
     *
     * @return
     */
    public String getTfTaxPayer() {
        return tfTaxPayer.getText().split(" : ")[0];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnSaveAgreement = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        tfAgreementNumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfDateOfExpiration = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfAmountOfDebt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnSetTaxpayer = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        tfTaxPayer = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tfVehicle = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        tfProperty = new javax.swing.JTextField();
        cmbSetConcept = new javax.swing.JComboBox<>();
        cmbSetCuots = new javax.swing.JComboBox<>();
        btnSetVehicle = new javax.swing.JButton();
        btnSetProperty = new javax.swing.JButton();
        btnEraseTaxPayer = new javax.swing.JButton();
        btnEraseVehicle = new javax.swing.JButton();
        btnEraseProperty = new javax.swing.JButton();
        btnDateOfCreation = new javax.swing.JButton();
        btnDateOfExpiration = new javax.swing.JButton();
        tfDateOfCreation = new javax.swing.JTextField();
        btnNewTaxpayer = new javax.swing.JButton();
        btnNewVehicle = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfDescription = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("INFORMACION DEL CONVENIO");
        setResizable(false);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(null);

        btnSaveAgreement.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSaveAgreement.setText("Guardar datos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 587, Short.MAX_VALUE)
                .addComponent(btnSaveAgreement))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnSaveAgreement)
                .addGap(14, 14, 14))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        tfAgreementNumber.setEditable(false);
        tfAgreementNumber.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tfAgreementNumber.setForeground(new java.awt.Color(0, 0, 0));
        tfAgreementNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nro. Convenio :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Concepto :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Fecha Vencimiento :");

        tfDateOfExpiration.setEditable(false);
        tfDateOfExpiration.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfDateOfExpiration.setForeground(new java.awt.Color(0, 0, 0));
        tfDateOfExpiration.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Cantidad de cuotas :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Fecha Efectuacion  :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Monto de la deuda :");

        tfAmountOfDebt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfAmountOfDebt.setForeground(new java.awt.Color(0, 0, 0));
        tfAmountOfDebt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfAmountOfDebt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfAmountOfDebtKeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Descripcion :");

        btnSetTaxpayer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSetTaxpayer.setText("...");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Titular :");

        tfTaxPayer.setEditable(false);
        tfTaxPayer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tfTaxPayer.setForeground(new java.awt.Color(0, 0, 0));
        tfTaxPayer.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("Vehiculo:");

        tfVehicle.setEditable(false);
        tfVehicle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tfVehicle.setForeground(new java.awt.Color(0, 0, 0));
        tfVehicle.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setText("Terreno / Inmueble :");

        tfProperty.setEditable(false);
        tfProperty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tfProperty.setForeground(new java.awt.Color(0, 0, 0));
        tfProperty.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cmbSetConcept.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbSetConcept.setForeground(new java.awt.Color(0, 0, 0));

        cmbSetCuots.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbSetCuots.setForeground(new java.awt.Color(0, 0, 0));
        cmbSetCuots.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));

        btnSetVehicle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSetVehicle.setText("...");

        btnSetProperty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSetProperty.setText("...");

        btnEraseTaxPayer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEraseTaxPayer.setForeground(new java.awt.Color(255, 0, 0));
        btnEraseTaxPayer.setText("X");
        btnEraseTaxPayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEraseTaxPayerActionPerformed(evt);
            }
        });

        btnEraseVehicle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEraseVehicle.setForeground(new java.awt.Color(255, 0, 0));
        btnEraseVehicle.setText("X");

        btnEraseProperty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEraseProperty.setForeground(new java.awt.Color(255, 0, 0));
        btnEraseProperty.setText("X");

        btnDateOfCreation.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDateOfCreation.setText("...");
        btnDateOfCreation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDateOfCreationActionPerformed(evt);
            }
        });

        btnDateOfExpiration.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDateOfExpiration.setText("...");
        btnDateOfExpiration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDateOfExpirationActionPerformed(evt);
            }
        });

        tfDateOfCreation.setEditable(false);
        tfDateOfCreation.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfDateOfCreation.setForeground(new java.awt.Color(0, 0, 0));
        tfDateOfCreation.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnNewTaxpayer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNewTaxpayer.setText("Nuevo");

        btnNewVehicle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNewVehicle.setText("Nuevo");

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Nuevo");

        tfDescription.setColumns(20);
        tfDescription.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfDescription.setForeground(new java.awt.Color(0, 0, 0));
        tfDescription.setRows(5);
        jScrollPane1.setViewportView(tfDescription);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbSetConcept, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfAgreementNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfProperty, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfVehicle))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(btnNewVehicle)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnSetVehicle))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnSetProperty))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfTaxPayer, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel22))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnNewTaxpayer)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnSetTaxpayer)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnEraseVehicle)
                                .addComponent(btnEraseProperty, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(btnEraseTaxPayer, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel12)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfDateOfCreation, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDateOfCreation))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfDateOfExpiration, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDateOfExpiration)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbSetCuots, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfAmountOfDebt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAgreementNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSetConcept, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(btnDateOfCreation)
                            .addComponent(tfDateOfCreation, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfDateOfExpiration, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(btnDateOfExpiration)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tfAmountOfDebt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cmbSetCuots, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTaxPayer, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEraseTaxPayer)
                    .addComponent(btnNewTaxpayer)
                    .addComponent(btnSetTaxpayer))
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSetVehicle)
                    .addComponent(btnEraseVehicle)
                    .addComponent(btnNewVehicle))
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfProperty, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSetProperty)
                    .addComponent(btnEraseProperty)
                    .addComponent(jButton3))
                .addGap(49, 49, 49))
        );

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfAmountOfDebtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfAmountOfDebtKeyReleased
        if ((!this.tfAmountOfDebt.getText().equals("")) && (!this.tfAmountOfDebt.getText().contains("$"))) {
            this.tfAmountOfDebt.setText("$ " + this.tfAmountOfDebt.getText());
        }
    }//GEN-LAST:event_tfAmountOfDebtKeyReleased

    /**
     * Shows the date chooser and captures the selected date.
     */
    public void showDateChooser() {
        this.dateChooserDialog1 = new DateChooserDialog();
        this.dateChooserDialog1.showDialog(this);
    }

    private void btnDateOfCreationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDateOfCreationActionPerformed
        showDateChooser();
        Calendar calendar = this.dateChooserDialog1.getSelectedDate();
        this.tfDateOfCreation.setText(calendar.get(Calendar.YEAR) + "-" + (calendar.get(Calendar.MONTH) + 1)
                + "-" + calendar.get(Calendar.DAY_OF_MONTH));
    }//GEN-LAST:event_btnDateOfCreationActionPerformed

    private void btnDateOfExpirationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDateOfExpirationActionPerformed
        showDateChooser();
        Calendar calendar = this.dateChooserDialog1.getSelectedDate();
        this.tfDateOfExpiration.setText(calendar.get(Calendar.YEAR) + "-" + (calendar.get(Calendar.MONTH) + 1)
                + "-" + calendar.get(Calendar.DAY_OF_MONTH));
    }//GEN-LAST:event_btnDateOfExpirationActionPerformed

    //Will set on blank tfTaxPayer
    private void btnEraseTaxPayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEraseTaxPayerActionPerformed
        tfTaxPayer.setText("");
    }//GEN-LAST:event_btnEraseTaxPayerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgreementRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgreementRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgreementRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgreementRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgreementRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDateOfCreation;
    private javax.swing.JButton btnDateOfExpiration;
    private javax.swing.JButton btnEraseProperty;
    private javax.swing.JButton btnEraseTaxPayer;
    private javax.swing.JButton btnEraseVehicle;
    private javax.swing.JButton btnNewTaxpayer;
    private javax.swing.JButton btnNewVehicle;
    private javax.swing.JButton btnSaveAgreement;
    private javax.swing.JButton btnSetProperty;
    private javax.swing.JButton btnSetTaxpayer;
    private javax.swing.JButton btnSetVehicle;
    private javax.swing.JComboBox<String> cmbSetConcept;
    private javax.swing.JComboBox<String> cmbSetCuots;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfAgreementNumber;
    private javax.swing.JTextField tfAmountOfDebt;
    private javax.swing.JTextField tfDateOfCreation;
    private javax.swing.JTextField tfDateOfExpiration;
    private javax.swing.JTextArea tfDescription;
    private javax.swing.JTextField tfProperty;
    private javax.swing.JTextField tfTaxPayer;
    private javax.swing.JTextField tfVehicle;
    // End of variables declaration//GEN-END:variables
}
