package View;

import Controller.DetailControl;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alejandro Juarez
 */
public class ConceptsList extends javax.swing.JFrame {

    /**
     * Creates new form ConceptsDetails
     */
    public ConceptsList() {
        initComponents();
    }

    /**
     * Sets the controller of this view.
     *
     * @param control
     */
    public void setController(DetailControl control) {
        btnRegisterConcept.addActionListener(control);
        btnRegisterConcept.setActionCommand("CONCEPT_REGISTRATION");
        btnDeleteConcept.addActionListener(control);
        btnDeleteConcept.setActionCommand("DELETE_CONCEPT");
    }

    /**
     * Gets the information of the selected row.
     *
     * @return
     */
    public String getSelectedConcept() {
        return tblConceptsDetail.getValueAt(tblConceptsDetail.getSelectedRow(), 0).toString();
    }

    /**
     * Will set the table model on this view.
     *
     * @param model
     */
    public void setTableModel(DefaultTableModel model) {
        //Indicamos la alineacion de las columnas
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.CENTER); //CENTER o LEFT
        tblConceptsDetail.setModel(model);  //Setting model
        tblConceptsDetail.setRowHeight(25); //Setting rows height
        tblConceptsDetail.setFont(new java.awt.Font("Tahoma", 0, 18)); //Changing font
        tblConceptsDetail.getTableHeader().setReorderingAllowed(false); //Disabling reordering columns
        //Indico la columna que quiero alinear siendo 1 el numero de columna
        for (int i = 0; i < tblConceptsDetail.getColumnCount(); i++) {
            tblConceptsDetail.getColumnModel().getColumn(i).setCellRenderer(tcr);
        }
        tblConceptsDetail.getColumnModel().getColumn(0).setMaxWidth(400);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnRegisterConcept = new javax.swing.JButton();
        btnModifyConcept = new javax.swing.JButton();
        btnDeleteConcept = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblConceptsDetail = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DETALLE DE CONCEPTOS");
        setResizable(false);

        jPanel1.setBorder(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnRegisterConcept.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegisterConcept.setText("Registrar");
        btnRegisterConcept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterConceptActionPerformed(evt);
            }
        });

        btnModifyConcept.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnModifyConcept.setText("Modificar");
        btnModifyConcept.setEnabled(false);

        btnDeleteConcept.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDeleteConcept.setText("Eliminar");
        btnDeleteConcept.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegisterConcept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModifyConcept, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(btnDeleteConcept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(199, Short.MAX_VALUE)
                .addComponent(btnRegisterConcept)
                .addGap(18, 18, 18)
                .addComponent(btnModifyConcept)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteConcept)
                .addGap(188, 188, 188))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tblConceptsDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblConceptsDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblConceptsDetailMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblConceptsDetail);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterConceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterConceptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegisterConceptActionPerformed

    private void tblConceptsDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblConceptsDetailMouseClicked
        if (tblConceptsDetail.getSelectedRow() != -1) {
            btnDeleteConcept.setEnabled(true);
        }
    }//GEN-LAST:event_tblConceptsDetailMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteConcept;
    private javax.swing.JButton btnModifyConcept;
    private javax.swing.JButton btnRegisterConcept;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblConceptsDetail;
    // End of variables declaration//GEN-END:variables
}
