package View;

import Controller.RegistrationControl;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Alejandro Juarez
 */
public class TaxpayerSelection extends javax.swing.JDialog {

    /**
     * Creates new form
     *
     * @param parent
     * @param modal
     */
    public TaxpayerSelection(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * Sets the controller of this view.
     *
     * @param control
     */
    public void setController(RegistrationControl control) {
        btnSelection.addActionListener(control);
        btnSelection.setActionCommand("TAXPAYER_SELECTED");
        tfSearch.addKeyListener(control);
    }

    /**
     * Gets the information of the selected row.
     *
     * @return
     */
    public String getSelectedRecord() {
        String chain = "";
        for (int i = 0; i < tblTaxPayers.getColumnCount(); i++) {
            if (i == tblTaxPayers.getColumnCount() - 1) {
                chain += (String) tblTaxPayers.getValueAt(tblTaxPayers.getSelectedRow(), i);
            } else {
                chain += (String) tblTaxPayers.getValueAt(tblTaxPayers.getSelectedRow(), i) + " : ";
            }
        }
        return chain;
    }

    /**
     * Will filter taxpayers table.
     */
    public void filterTaxpayers() {
        TableRowSorter trsFiltro = new TableRowSorter(tblTaxPayers.getModel());
        if (chkDocNumber.isSelected() || chkLastname.isSelected()) {
            if (chkDocNumber.isSelected()) {
                trsFiltro.setRowFilter(RowFilter.regexFilter(tfSearch.getText().toUpperCase(), 0));
            } else {
                trsFiltro.setRowFilter(RowFilter.regexFilter(tfSearch.getText().toUpperCase(), 2));
            }
        }
        tblTaxPayers.setRowSorter(trsFiltro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTaxPayers = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        tfSearch = new javax.swing.JTextField();
        chkLastname = new javax.swing.JCheckBox();
        chkDocNumber = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        btnSelection = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SELECCION DEL TITULAR", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setLayout(new java.awt.BorderLayout());

        tblTaxPayers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblTaxPayers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTaxPayersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTaxPayers);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tfSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfSearch.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        chkLastname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chkLastname.setForeground(new java.awt.Color(0, 0, 0));
        chkLastname.setText("Busqueda por apellido");
        chkLastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLastnameActionPerformed(evt);
            }
        });

        chkDocNumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chkDocNumber.setForeground(new java.awt.Color(0, 0, 0));
        chkDocNumber.setSelected(true);
        chkDocNumber.setText("Busqueda por Nro. Doc");
        chkDocNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDocNumberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(chkDocNumber)
                .addGap(18, 18, 18)
                .addComponent(chkLastname)
                .addGap(18, 18, 18)
                .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkLastname)
                    .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkDocNumber))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        btnSelection.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSelection.setText("Seleccionar");
        btnSelection.setEnabled(false);

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(618, Short.MAX_VALUE)
                .addComponent(btnCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSelection)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelection)
                    .addComponent(btnCancel))
                .addGap(14, 14, 14))
        );

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 873, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     *
     * @param evt
     */
    private void tblTaxPayersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTaxPayersMouseClicked
        if (tblTaxPayers.getSelectedRow() != -1) {
            btnSelection.setEnabled(true);
        }
    }//GEN-LAST:event_tblTaxPayersMouseClicked

    /**
     *
     * @param evt
     */
    private void chkDocNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDocNumberActionPerformed
        chkLastname.setSelected(false);
    }//GEN-LAST:event_chkDocNumberActionPerformed

    /**
     *
     * @param evt
     */
    private void chkLastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLastnameActionPerformed
        chkDocNumber.setSelected(false);
    }//GEN-LAST:event_chkLastnameActionPerformed

    /**
     * Will set the model for the table.
     *
     * @param model
     */
    public void setTableModel(DefaultTableModel model) {
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.CENTER); //CENTER o LEFT
        tblTaxPayers.setModel(model);  //Setting model
        tblTaxPayers.setRowHeight(25); //Setting rows height
        tblTaxPayers.setFont(new java.awt.Font("Tahoma", 0, 18)); //Changing font
        tblTaxPayers.getTableHeader().setReorderingAllowed(false); //Disabling reordering columns
        for (int i = 0; i < tblTaxPayers.getColumnCount(); i++) {
            tblTaxPayers.getColumnModel().getColumn(i).setCellRenderer(tcr);
        }
    }

    /**
     *
     * @return
     */
    public JTextField getTfSearch() {
        return this.tfSearch;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSelection;
    private javax.swing.JCheckBox chkDocNumber;
    private javax.swing.JCheckBox chkLastname;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTaxPayers;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables

}
