package View;

import Controller.UserControl;
import javax.swing.JOptionPane;

/**
 *
 * @author Alejandro Juarez
 */
public class UserRegistration extends javax.swing.JDialog {

    /**
     * Creates new form TaxpayerRegistration
     *
     * @param parent
     * @param modal
     */
    public UserRegistration(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * Will set the controller for this view.
     *
     * @param control
     */
    public void setController(UserControl control) {
        this.btnSaveTaxpayer.addActionListener(control);
        this.btnSaveTaxpayer.setActionCommand("SAVE_USER");
    }

    /**
     * Will verify if the field are completed or not.
     *
     * @return
     */
    public boolean verifyInformation() {

        if (tfNames.getText().equals("")) {
            JOptionPane.showMessageDialog(
                    this,
                    "El nombre del usuario es obligatorio",
                    "Advertencia",
                    JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if (tfLastname.getText().equals("")) {
            JOptionPane.showMessageDialog(
                    this,
                    "EL apellido del usuario es obligatorio",
                    "Advertencia",
                    JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if (tfNickName.getText().equals("")) {
            JOptionPane.showMessageDialog(
                    this,
                    "El nick del usuario es obligatorio",
                    "Advertencia",
                    JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if (tfPassword.getText().equals("")) {
            JOptionPane.showMessageDialog(
                    this,
                    "La contraseña es obligatoria",
                    "Advertencia",
                    JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;

    }

    /**
     *
     * @return
     */
    public String getTfNames() {
        return tfNames.getText().toUpperCase();
    }

    /**
     *
     * @return
     */
    public String getTfLastname() {
        return tfLastname.getText().toUpperCase();
    }

    /**
     *
     * @return
     */
    public String getTfNickName() {
        return tfNickName.getText();
    }

    /**
     *
     * @return
     */
    public String getTfPassword() {
        return tfPassword.getText();
    }

    /**
     *
     * @return
     */
    public boolean getChkAdministrator() {
        return chkAdministrator.isSelected();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnSaveTaxpayer = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        tfNames = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfLastname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfNickName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfPassword = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        chkAdministrator = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153), 3));
        jPanel1.setLayout(new java.awt.BorderLayout());

        btnSaveTaxpayer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSaveTaxpayer.setText("Guardar");

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(310, Short.MAX_VALUE)
                .addComponent(btnCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSaveTaxpayer)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveTaxpayer)
                    .addComponent(btnCancel))
                .addGap(14, 14, 14))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTRO USUARIO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        tfNames.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfNames.setForeground(new java.awt.Color(0, 0, 0));
        tfNames.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNames.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNamesKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombres :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Apellido :");

        tfLastname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfLastname.setForeground(new java.awt.Color(0, 0, 0));
        tfLastname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfLastname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfLastnameKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nick usuario :");

        tfNickName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfNickName.setForeground(new java.awt.Color(0, 0, 0));
        tfNickName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNickName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNickNameKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Contraseña :");

        tfPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfPassword.setForeground(new java.awt.Color(0, 0, 0));
        tfPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Seleccione esta opcion si el usuario es administrador :");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfLastname, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                            .addComponent(tfNames, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNickName)
                            .addComponent(tfPassword, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkAdministrator)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNames, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNickName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(chkAdministrator))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Will close this view.
     *
     * @param evt
     */
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void tfNamesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNamesKeyTyped
        if (tfNames.getText().length() == 35) {
            evt.consume();
        }
        char c = evt.getKeyChar();
        if (Character.isLetter(c) || c == ' ') {
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_tfNamesKeyTyped

    private void tfLastnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfLastnameKeyTyped
        if (tfLastname.getText().length() == 25) {
            evt.consume();
        }
        char c = evt.getKeyChar();
        if (Character.isLetter(c) || c == ' ') {
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_tfLastnameKeyTyped

    private void tfNickNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNickNameKeyTyped
        if (tfLastname.getText().length() == 15) {
            evt.consume();
        }
        char c = evt.getKeyChar();
        if (Character.isDigit(c) || Character.isLetter(c)) {
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_tfNickNameKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSaveTaxpayer;
    private javax.swing.JCheckBox chkAdministrator;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField tfLastname;
    private javax.swing.JTextField tfNames;
    private javax.swing.JTextField tfNickName;
    private javax.swing.JTextField tfPassword;
    // End of variables declaration//GEN-END:variables
}
