package View;

import Controller.RegistrationControl;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Alejandro Juarez
 */
public class VehicleSelection extends javax.swing.JDialog {

    /**
     * Creates new form
     *
     * @param parent
     * @param modal
     */
    public VehicleSelection(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * Sets the controller of this view.
     *
     * @param control
     */
    public void setController(RegistrationControl control) {
        btnSelection.addActionListener(control);
        btnSelection.setActionCommand("VEHICLE_SELECTED");
        tfSearch.addKeyListener(control);
    }

    /**
     * Gets the information of the selected row.
     *
     * @return
     */
    public String getSelectedRecord() {
        String chain = "";
        for (int i = 0; i < tblVehicle.getColumnCount(); i++) {
            if (i == tblVehicle.getColumnCount() - 1) {
                chain += (String) tblVehicle.getValueAt(tblVehicle.getSelectedRow(), i);
            } else {
                chain += (String) tblVehicle.getValueAt(tblVehicle.getSelectedRow(), i) + " : ";
            }
        }
        return chain;
    }

    /**
     * Will filter vehicle table.
     */
    public void filterVehicles() {
        TableRowSorter trsFiltro = new TableRowSorter(tblVehicle.getModel());
        if (chkDomain.isSelected() || chkModel.isSelected()) {
            if (chkDomain.isSelected()) {
                trsFiltro.setRowFilter(RowFilter.regexFilter(tfSearch.getText().toUpperCase(), 1));
            } else {
                trsFiltro.setRowFilter(RowFilter.regexFilter(tfSearch.getText().toUpperCase(), 2));
            }
        }
        tblVehicle.setRowSorter(trsFiltro);
    }

    /**
     *
     * @return
     */
    public JTextField getTfSearch() {
        return this.tfSearch;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVehicle = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        tfSearch = new javax.swing.JTextField();
        chkModel = new javax.swing.JCheckBox();
        chkDomain = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        btnSelection = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SELECCION DEL TITULAR", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setLayout(new java.awt.BorderLayout());

        tblVehicle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblVehicle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVehicleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVehicle);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tfSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfSearch.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        chkModel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chkModel.setForeground(new java.awt.Color(0, 0, 0));
        chkModel.setText("Busqueda por modelo");
        chkModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkModelActionPerformed(evt);
            }
        });

        chkDomain.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chkDomain.setForeground(new java.awt.Color(0, 0, 0));
        chkDomain.setSelected(true);
        chkDomain.setText("Busqueda por dominio");
        chkDomain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDomainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(chkDomain)
                .addGap(18, 18, 18)
                .addComponent(chkModel)
                .addGap(18, 18, 18)
                .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkModel)
                    .addComponent(chkDomain))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        btnSelection.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSelection.setText("Seleccionar");
        btnSelection.setEnabled(false);

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(618, Short.MAX_VALUE)
                .addComponent(btnCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSelection)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelection)
                    .addComponent(btnCancel))
                .addGap(14, 14, 14))
        );

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 873, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     * @param evt
     */
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     *
     * @param evt
     */
    private void tblVehicleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVehicleMouseClicked
        if (tblVehicle.getSelectedRow() != -1) {
            btnSelection.setEnabled(true);
        }
    }//GEN-LAST:event_tblVehicleMouseClicked

    /**
     *
     * @param evt
     */
    private void chkModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkModelActionPerformed
        chkDomain.setSelected(false);
    }//GEN-LAST:event_chkModelActionPerformed

    /**
     *
     * @param evt
     */
    private void chkDomainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDomainActionPerformed
        chkModel.setSelected(false);
    }//GEN-LAST:event_chkDomainActionPerformed

    /**
     * Will set the model for the table.
     *
     * @param model
     */
    public void setTableModel(DefaultTableModel model) {
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.CENTER); //CENTER o LEFT
        tblVehicle.setModel(model);  //Setting model
        tblVehicle.setRowHeight(25); //Setting rows height
        tblVehicle.setFont(new java.awt.Font("Tahoma", 0, 18)); //Changing font
        tblVehicle.getTableHeader().setReorderingAllowed(false); //Disabling reordering columns
        for (int i = 0; i < tblVehicle.getColumnCount(); i++) {
            tblVehicle.getColumnModel().getColumn(i).setCellRenderer(tcr);
        }
        //Making first column not visible for users.
        tblVehicle.getColumn(tblVehicle.getColumnName(0)).setWidth(0);
        tblVehicle.getColumn(tblVehicle.getColumnName(0)).setMinWidth(0);
        tblVehicle.getColumn(tblVehicle.getColumnName(0)).setMaxWidth(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSelection;
    private javax.swing.JCheckBox chkDomain;
    private javax.swing.JCheckBox chkModel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVehicle;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables

}
