package Model.DTO;
// Generated Feb 16, 2019 12:20:15 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ActionCommitted generated by hbm2java
 */
public class ActionCommitted  implements java.io.Serializable {


     private long idAction;
     private User user;
     private String actionCommitted;
     private Date date;
     private String description;

    public ActionCommitted() {
    }

	
    public ActionCommitted(long idAction, User user, String actionCommitted, Date date) {
        this.idAction = idAction;
        this.user = user;
        this.actionCommitted = actionCommitted;
        this.date = date;
    }
    public ActionCommitted(long idAction, User user, String actionCommitted, Date date, String description) {
       this.idAction = idAction;
       this.user = user;
       this.actionCommitted = actionCommitted;
       this.date = date;
       this.description = description;
    }
   
    public long getIdAction() {
        return this.idAction;
    }
    
    public void setIdAction(long idAction) {
        this.idAction = idAction;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getActionCommitted() {
        return this.actionCommitted;
    }
    
    public void setActionCommitted(String actionCommitted) {
        this.actionCommitted = actionCommitted;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


