package Model.DTO;
// Generated Feb 4, 2019 1:15:39 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Agreement generated by hbm2java
 */
public class Agreement implements java.io.Serializable {

    private Long idAgreementNumber;
    private Concept concept;
    private Property property;
    private Taxpayer taxpayer;
    private Vehicle vehicle;
    private double amountOfDebt;
    private int cuotsNumber;
    private Date creationDate;
    private Date expirationDate;
    private String state;
    private String description;
    private Set payments = new HashSet(0);

    public Agreement() {
    }

    /**
     * Added by me.
     *
     * @param amountOfDebt
     * @param cuotsNumber
     * @param creationDate
     * @param expirationDate
     * @param state
     */
    public Agreement(double amountOfDebt, int cuotsNumber, Date creationDate, Date expirationDate, String state) {
        this.amountOfDebt = amountOfDebt;
        this.cuotsNumber = cuotsNumber;
        this.creationDate = creationDate;
        this.expirationDate = expirationDate;
        this.state = state;
    }

    /**
     * Added by me.
     *
     * @param conceptCode
     */
    public void setConcept(Integer conceptCode) {
        this.concept = new Concept(conceptCode);
    }

    /**
     * Added by me.
     *
     * @return
     */
    public long getConceptID() {
        return this.concept.getIdConceptCode();
    }

    /**
     * Added by me.
     *
     * @param taxPayerDocNumeber
     */
    public void setTaxpayer(Long taxPayerDocNumeber) {
        this.taxpayer = new Taxpayer(taxPayerDocNumeber);
    }

    /**
     * Added by me.
     *
     * @return
     */
    public long getTaxPayerID() {
        return this.taxpayer.getIdDocNumber();
    }

    /**
     * Added by me.
     *
     * @param domain
     */
    public void setVehicle(String domain) {
        this.vehicle = new Vehicle(domain);
    }

    /**
     * Added by me.
     *
     * @return
     */
    public long getVehicleID() {
        return this.vehicle.getIdVehicle();
    }

    public Agreement(Concept concept, Taxpayer taxpayer, double amountOfDebt, int cuotsNumber, Date creationDate, Date expirationDate, String state) {
        this.concept = concept;
        this.taxpayer = taxpayer;
        this.amountOfDebt = amountOfDebt;
        this.cuotsNumber = cuotsNumber;
        this.creationDate = creationDate;
        this.expirationDate = expirationDate;
        this.state = state;
    }

    public Agreement(Concept concept, Property property, Taxpayer taxpayer, Vehicle vehicle, double amountOfDebt, int cuotsNumber, Date creationDate, Date expirationDate, String state, String description, Set payments) {
        this.concept = concept;
        this.property = property;
        this.taxpayer = taxpayer;
        this.vehicle = vehicle;
        this.amountOfDebt = amountOfDebt;
        this.cuotsNumber = cuotsNumber;
        this.creationDate = creationDate;
        this.expirationDate = expirationDate;
        this.state = state;
        this.description = description;
        this.payments = payments;
    }

    public Long getIdAgreementNumber() {
        return this.idAgreementNumber;
    }

    public void setIdAgreementNumber(Long idAgreementNumber) {
        this.idAgreementNumber = idAgreementNumber;
    }

    public Concept getConcept() {
        return this.concept;
    }

    public void setConcept(Concept concept) {
        this.concept = concept;
    }

    public Property getProperty() {
        return this.property;
    }

    public void setProperty(Property property) {
        this.property = property;
    }

    public Taxpayer getTaxpayer() {
        return this.taxpayer;
    }

    public void setTaxpayer(Taxpayer taxpayer) {
        this.taxpayer = taxpayer;
    }

    public Vehicle getVehicle() {
        return this.vehicle;
    }

    public void setVehicle(Vehicle vehicle) {
        this.vehicle = vehicle;
    }

    public double getAmountOfDebt() {
        return this.amountOfDebt;
    }

    public void setAmountOfDebt(double amountOfDebt) {
        this.amountOfDebt = amountOfDebt;
    }

    public int getCuotsNumber() {
        return this.cuotsNumber;
    }

    public void setCuotsNumber(int cuotsNumber) {
        this.cuotsNumber = cuotsNumber;
    }

    public Date getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    public Date getExpirationDate() {
        return this.expirationDate;
    }

    public void setExpirationDate(Date expirationDate) {
        this.expirationDate = expirationDate;
    }

    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Set getPayments() {
        return this.payments;
    }

    public void setPayments(Set payments) {
        this.payments = payments;
    }

}
