package Model.DTO;
// Generated Feb 16, 2019 12:20:15 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Concept generated by hbm2java
 */
public class Concept implements java.io.Serializable {

    private int idConceptCode;
    private String conceptName;
    private String description;
    private Set agreements = new HashSet(0);

    /**
     * Added by me.
     *
     * @param conceptCode
     */
    public Concept(Integer conceptCode) {
        this.idConceptCode = conceptCode;
    }

    /**
     * Added by me.
     *
     * @param idConceptCode
     * @param conceptName
     * @param description
     */
    public Concept(int idConceptCode, String conceptName, String description) {
        this.idConceptCode = idConceptCode;
        this.conceptName = conceptName;
        this.description = description;
    }

    /**
     * Adde by me.
     *
     * @return
     */
    public int getConceptID() {
        return this.idConceptCode;
    }

    public Concept() {
    }

    public Concept(int idConceptCode, String conceptName) {
        this.idConceptCode = idConceptCode;
        this.conceptName = conceptName;
    }

    public Concept(int idConceptCode, String conceptName, String description, Set agreements) {
        this.idConceptCode = idConceptCode;
        this.conceptName = conceptName;
        this.description = description;
        this.agreements = agreements;
    }

    public int getIdConceptCode() {
        return this.idConceptCode;
    }

    public void setIdConceptCode(int idConceptCode) {
        this.idConceptCode = idConceptCode;
    }

    public String getConceptName() {
        return this.conceptName;
    }

    public void setConceptName(String conceptName) {
        this.conceptName = conceptName;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Set getAgreements() {
        return this.agreements;
    }

    public void setAgreements(Set agreements) {
        this.agreements = agreements;
    }

}
