package Model.DTO;
// Generated Feb 16, 2019 12:20:15 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * LandProperty generated by hbm2java
 */
public class LandProperty  implements java.io.Serializable {


     private Long idProperty;
     private String apple;
     private String batch;
     private String adjudicationDecree;
     private Byte wasteland;
     private Set agreements = new HashSet(0);

    public LandProperty() {
    }

    public LandProperty(String apple, String batch, String address, String adjudicationDecree) {
        this.apple = apple;
        this.batch = batch;
        this.adjudicationDecree = adjudicationDecree;
    }
	
    public LandProperty(String apple, String batch) {
        this.apple = apple;
        this.batch = batch;
    }
    
    public LandProperty(String apple, String batch, String adjudicationDecree, Byte wasteland, Set agreements) {
       this.apple = apple;
       this.batch = batch;
       this.adjudicationDecree = adjudicationDecree;
       this.wasteland = wasteland;
       this.agreements = agreements;
    }
   
    public Long getIdProperty() {
        return this.idProperty;
    }
    
    public void setIdProperty(Long idProperty) {
        this.idProperty = idProperty;
    }
    public String getApple() {
        return this.apple;
    }
    
    public void setApple(String apple) {
        this.apple = apple;
    }
    public String getBatch() {
        return this.batch;
    }
    
    public void setBatch(String batch) {
        this.batch = batch;
    }
    public String getAdjudicationDecree() {
        return this.adjudicationDecree;
    }
    
    public void setAdjudicationDecree(String adjudicationDecree) {
        this.adjudicationDecree = adjudicationDecree;
    }
    public Byte getWasteland() {
        return this.wasteland;
    }
    
    public void setWasteland(Byte wasteland) {
        this.wasteland = wasteland;
    }
    public Set getAgreements() {
        return this.agreements;
    }
    
    public void setAgreements(Set agreements) {
        this.agreements = agreements;
    }




}


