package Model.DTO;
// Generated Feb 22, 2019 2:08:50 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * LandProperty generated by hbm2java
 */
public class LandProperty implements java.io.Serializable {

    private Long idProperty;
    private String apple;
    private String batch;
    private String adjudicationDecree;
    private Byte wasteland;
    private String address;
    private Set agreements = new HashSet(0);

    /**
     * Added by me.
     *
     * @param landPropertyIdentifier
     */
    public LandProperty(Long landPropertyIdentifier) {
        this.idProperty = landPropertyIdentifier;
    }
    
    /**
     * Added by me.
     * @param apple
     * @param batch
     * @param decree 
     */
    public LandProperty(String apple, String batch, String decree) {
        this.apple = apple;
        this.batch = batch;
        this.adjudicationDecree = decree;
    }

    public LandProperty() {
    }

    public LandProperty(String apple, String batch, String adjudicationDecree, Byte wasteland, String address, Set agreements) {
        this.apple = apple;
        this.batch = batch;
        this.adjudicationDecree = adjudicationDecree;
        this.wasteland = wasteland;
        this.address = address;
        this.agreements = agreements;
    }

    public Long getIdProperty() {
        return this.idProperty;
    }

    public void setIdProperty(Long idProperty) {
        this.idProperty = idProperty;
    }

    public String getApple() {
        return this.apple;
    }

    public void setApple(String apple) {
        this.apple = apple;
    }

    public String getBatch() {
        return this.batch;
    }

    public void setBatch(String batch) {
        this.batch = batch;
    }

    public String getAdjudicationDecree() {
        return this.adjudicationDecree;
    }

    public void setAdjudicationDecree(String adjudicationDecree) {
        this.adjudicationDecree = adjudicationDecree;
    }

    public Byte getWasteland() {
        return this.wasteland;
    }

    public void setWasteland(Byte wasteland) {
        this.wasteland = wasteland;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Set getAgreements() {
        return this.agreements;
    }

    public void setAgreements(Set agreements) {
        this.agreements = agreements;
    }

}
