package Model.DTO;
// Generated Feb 22, 2019 2:08:50 PM by Hibernate Tools 4.3.1



/**
 * Payment generated by hbm2java
 */
public class Payment  implements java.io.Serializable {


     private Long idPaymentNumber;
     private Agreement agreement;
     private Receipt receipt;
     private int paidFee;

    public Payment() {
    }

    public Payment(Agreement agreement, Receipt receipt, int paidFee) {
       this.agreement = agreement;
       this.receipt = receipt;
       this.paidFee = paidFee;
    }
   
    public Long getIdPaymentNumber() {
        return this.idPaymentNumber;
    }
    
    public void setIdPaymentNumber(Long idPaymentNumber) {
        this.idPaymentNumber = idPaymentNumber;
    }
    public Agreement getAgreement() {
        return this.agreement;
    }
    
    public void setAgreement(Agreement agreement) {
        this.agreement = agreement;
    }
    public Receipt getReceipt() {
        return this.receipt;
    }
    
    public void setReceipt(Receipt receipt) {
        this.receipt = receipt;
    }
    public int getPaidFee() {
        return this.paidFee;
    }
    
    public void setPaidFee(int paidFee) {
        this.paidFee = paidFee;
    }




}


