package Model.DTO;
// Generated Feb 28, 2019 11:12:19 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Receipt generated by hbm2java
 */
public class Receipt implements java.io.Serializable {

    private long idReceiptNumber;
    private Date date;
    private double amount;
    private Set payments = new HashSet(0);

    /**
     * Added by me.
     *
     * @param receiptNumber
     */
    public Receipt(Long receiptNumber) {
        this.idReceiptNumber = receiptNumber;
    }

    public Receipt() {
    }

    public Receipt(long idReceiptNumber, Date date, double amount) {
        this.idReceiptNumber = idReceiptNumber;
        this.date = date;
        this.amount = amount;
    }

    public Receipt(long idReceiptNumber, Date date, double amount, Set payments) {
        this.idReceiptNumber = idReceiptNumber;
        this.date = date;
        this.amount = amount;
        this.payments = payments;
    }

    public long getIdReceiptNumber() {
        return this.idReceiptNumber;
    }

    public void setIdReceiptNumber(long idReceiptNumber) {
        this.idReceiptNumber = idReceiptNumber;
    }

    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public double getAmount() {
        return this.amount;
    }

    public void setAmount(double amount) {
        this.amount = amount;
    }

    public Set getPayments() {
        return this.payments;
    }

    public void setPayments(Set payments) {
        this.payments = payments;
    }

}
