package Model.DTO;
// Generated Feb 16, 2019 12:20:15 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer idUser;
     private String names;
     private String lastname;
     private String nickName;
     private String password;
     private byte administrator;
     private Byte activeSession;
     private Byte writtenOff;
     private Set actionCommitteds = new HashSet(0);

    public User() {
    }

	
    public User(String names, String lastname, String nickName, String password, byte administrator) {
        this.names = names;
        this.lastname = lastname;
        this.nickName = nickName;
        this.password = password;
        this.administrator = administrator;
    }
    public User(String names, String lastname, String nickName, String password, byte administrator, Byte activeSession, Byte writtenOff, Set actionCommitteds) {
       this.names = names;
       this.lastname = lastname;
       this.nickName = nickName;
       this.password = password;
       this.administrator = administrator;
       this.activeSession = activeSession;
       this.writtenOff = writtenOff;
       this.actionCommitteds = actionCommitteds;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public String getNames() {
        return this.names;
    }
    
    public void setNames(String names) {
        this.names = names;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getNickName() {
        return this.nickName;
    }
    
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public byte getAdministrator() {
        return this.administrator;
    }
    
    public void setAdministrator(byte administrator) {
        this.administrator = administrator;
    }
    public Byte getActiveSession() {
        return this.activeSession;
    }
    
    public void setActiveSession(Byte activeSession) {
        this.activeSession = activeSession;
    }
    public Byte getWrittenOff() {
        return this.writtenOff;
    }
    
    public void setWrittenOff(Byte writtenOff) {
        this.writtenOff = writtenOff;
    }
    public Set getActionCommitteds() {
        return this.actionCommitteds;
    }
    
    public void setActionCommitteds(Set actionCommitteds) {
        this.actionCommitteds = actionCommitteds;
    }




}


