package Model.DTO;
// Generated Feb 7, 2019 9:37:40 AM by Hibernate Tools 4.3.1

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

    private Integer idUser;
    private String name;
    private String lastName;
    private String nickName;
    private String password;

    public User() {
    }

    public User(String name, String lastName, String nickName, String password) {
        this.name = name;
        this.lastName = lastName;
        this.nickName = nickName;
        this.password = password;
    }

    public Integer getIdUser() {
        return this.idUser;
    }

    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getNickName() {
        return this.nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

}
