package Model.DTO;
// Generated Feb 4, 2019 1:15:39 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Vehicle generated by hbm2java
 */
public class Vehicle implements java.io.Serializable {

    private long idVehicle;
    private String patentNumber;
    private String type;
    private Set agreements = new HashSet(0);

    public Vehicle() {
    }

    /**
     * Added by me.
     *
     * @param domain
     */
    public Vehicle(String domain) {

    }

    public Vehicle(long idVehicle, String patentNumber, String type) {
        this.idVehicle = idVehicle;
        this.patentNumber = patentNumber;
        this.type = type;
    }

    public Vehicle(long idVehicle, String patentNumber, String type, Set agreements) {
        this.idVehicle = idVehicle;
        this.patentNumber = patentNumber;
        this.type = type;
        this.agreements = agreements;
    }

    public long getIdVehicle() {
        return this.idVehicle;
    }

    public void setIdVehicle(long idVehicle) {
        this.idVehicle = idVehicle;
    }

    public String getPatentNumber() {
        return this.patentNumber;
    }

    public void setPatentNumber(String patentNumber) {
        this.patentNumber = patentNumber;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Set getAgreements() {
        return this.agreements;
    }

    public void setAgreements(Set agreements) {
        this.agreements = agreements;
    }

}
