package Model.DTO;
// Generated Feb 7, 2019 9:37:40 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Vehicle generated by hbm2java
 */
public class Vehicle implements java.io.Serializable {

    private long idVehicle;
    private String domain;
    private String type;
    private String fabricant;
    private String model;
    private Set agreements = new HashSet(0);

    /**
     * Added by me.
     *
     * @param domain
     */
    public Vehicle(String domain) {

    }

    public Vehicle() {
    }

    public Vehicle(long idVehicle, String domain, String type, String fabricant, String model) {
        this.idVehicle = idVehicle;
        this.domain = domain;
        this.type = type;
        this.fabricant = fabricant;
        this.model = model;
    }

    public Vehicle(long idVehicle, String domain, String type, String fabricant, String model, Set agreements) {
        this.idVehicle = idVehicle;
        this.domain = domain;
        this.type = type;
        this.fabricant = fabricant;
        this.model = model;
        this.agreements = agreements;
    }

    public long getIdVehicle() {
        return this.idVehicle;
    }

    public void setIdVehicle(long idVehicle) {
        this.idVehicle = idVehicle;
    }

    public String getDomain() {
        return this.domain;
    }

    public void setDomain(String domain) {
        this.domain = domain;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getFabricant() {
        return this.fabricant;
    }

    public void setFabricant(String fabricant) {
        this.fabricant = fabricant;
    }

    public String getModel() {
        return this.model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    public Set getAgreements() {
        return this.agreements;
    }

    public void setAgreements(Set agreements) {
        this.agreements = agreements;
    }

}
